\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{erc-B2}[2019/02/26 erc-B2]
\LoadClass{../erc}
\RequirePackage[left=2cm,top=1.5cm,bottom=1.5cm,right=2cm,headsep=.45cm,footskip=.8cm]{geometry}

\chead[Part B2]{Part B2}

\def\maketitle{\vspace*{.45cm}{\centering\bfseries\Large
ERC \erctype{} Grant \ercyear{}\\
Part B2\\
\textit{(\underline{not} evaluated in Step 1)}\par
%\normalfont\huge
%\vspace{.5cm}\@title\par
%\vspace{.7cm}\@acronym\par
%\normalfont\normalsize\raggedright\vspace{2cm}\begin{compactitem}
%\item \textbf{Principal investigator (PI):} \@author
%\item \textbf{Host institution:} \@institution
%\item \textbf{Proposal duration:} 60 months%
%\end{compactitem}
\par\vspace{1.2em}}
\noindent\textbf{Sections (a) and (b) of Part B2 should not exceed 14 pages. References do not count towards the page limits.}
}


\bonefalse
